---
- name: Load nginx install tasks
  ansible.builtin.import_tasks: install.yml

- name: Load nginx config tasks
  ansible.builtin.import_tasks: config.yml

- name: Load nginx service tasks
  ansible.builtin.import_tasks: service.yml
