---
- name: Configure Linux server for static app hosting
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: base
      tags:
        - base
    - role: nginx
      tags:
        - nginx
    - role: app
      tags:
        - app
    - role: ssh
      tags:
        - ssh
