---
base_packages:
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - rsync
  - tar
  - unzip
  - vim

base_firewall_enabled: true
base_fail2ban_enabled: true
base_ssh_port: 22

base_debian_firewall_package: ufw
base_redhat_firewall_package: firewalld
