---
- name: Load SSH validation tasks
  ansible.builtin.import_tasks: validate.yml

- name: Load SSH key tasks
  ansible.builtin.import_tasks: keys.yml

- name: Load SSH hardening tasks
  ansible.builtin.import_tasks: hardening.yml

- name: Load SSH service tasks
  ansible.builtin.import_tasks: service.yml
