---
- name: Load app validation tasks
  ansible.builtin.import_tasks: validate.yml

- name: Load app directory tasks
  ansible.builtin.import_tasks: directories.yml

- name: Load app tarball deployment tasks
  ansible.builtin.import_tasks: deploy_tarball.yml

- name: Load app git deployment tasks
  ansible.builtin.import_tasks: deploy_git.yml

- name: Load app permissions tasks
  ansible.builtin.import_tasks: permissions.yml
