---
- name: Load base package tasks
  ansible.builtin.import_tasks: packages.yml

- name: Load fail2ban tasks
  ansible.builtin.import_tasks: fail2ban.yml

- name: Load UFW tasks
  ansible.builtin.import_tasks: firewall_ufw.yml

- name: Load firewalld tasks
  ansible.builtin.import_tasks: firewall_firewalld.yml
